services:
  dockey:
    image: iamdockin/dockey # image is on Docker Hub
    container_name: dockey
    restart: unless-stopped
    ports:
      # Map port 8000 on the host to port 8000 in the container.
      # You can change the host port, e.g., "8080:8000".
      - "8000:8000"
    volumes:
      # Mount the Docker socket from the host into the container.
      # This is REQUIRED for Dockey to see and manage other containers.
      - /var/run/docker.sock:/var/run/docker.sock
